---
title: "Miniproject2:Thinktank Dataset"
author: "Team Kansas"
date: "March 18, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading Packages

```{r load.lib, message = FALSE, warning = FALSE}
library(magrittr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(broom)
library(nlme)
library(tibble)
library(NHANES)
library(gridExtra)
library(GGally)
library(viridis)
```

## Reading Data

```{r reading.data}
WTHH.df <- read.csv('DFP_WTHH_release.csv', stringsAsFactors = FALSE) %>%
            select(presvote16post, house3, weight_DFP, M4A, GREENJOB, WEALTH, MARLEG, ICE, GUNS, POP_1, POP_2, POP_3)
str(WTHH.df)
colSums(is.na(WTHH.df))

```

## Preprocessing
```{r preprocessing.data}

WTHH.df[WTHH.df[, 'presvote16post'] %in% c(3 : 7),]$presvote16post = 3
WTHH.df[WTHH.df[, 'house3'] == 3,]$house3 = 3
WTHH.df$presvote16post = WTHH.df$presvote16post - 1
WTHH.df$house3 = WTHH.df$house3 - 1
```

```{r creating.swings}
voting.groups <- c('Loyal Democrats', 'Loyal Republicans', 'Switch to D', 'Switch to R')
WTHH.df <- WTHH.df %>%
  mutate(voting.pattern = ifelse(presvote16post == 0 & house3 == 0, 'Loyal Democrats', ifelse(presvote16post == 1 & house3 == 1, 'Loyal Republicans', ifelse(presvote16post != 0 & house3 == 0, 'Switch to D', ifelse(presvote16post != 1 & house3 == 1, 'Switch to R', NA))))) %>%
    mutate(voting.pattern = factor(voting.pattern))

str(WTHH.df)
```


## Question 1

```{r gathering.data.1}
WTHH.df.gather <- WTHH.df %>%
                    gather("issue.variable", "value", -presvote16post, -house3, -weight_DFP, -POP_1, -POP_2, -POP_3, -voting.pattern) %>%
                      mutate(issue.variable = factor(issue.variable, levels = c('M4A', 'GREENJOB', 'WEALTH', 'MARLEG', 'ICE', 'GUNS'), 
                                                     labels = c('Medicare for All', 'A Green Jobs program', expression('A tax on wealth \n over $100 million'), 'Legalizing marijuana', expression('  Defunding Immigration \nand Customs Enforcement  '), 'Gun control')))

str(WTHH.df.gather)
```


```{r question.1, fig.width = 16, fig.height = 12, warning = FALSE}
WTHH.df.gather %>% filter(value != 6) %>%
  group_by(voting.pattern, issue.variable) %>%
    mutate(total.weight = sum(weight_DFP)) %>%
  ungroup() %>%
    mutate(new.weights = weight_DFP/total.weight) %>%
      filter(voting.pattern %in% c('Switch to D', 'Switch to R')) %>%
        ggplot(aes(x = value, group = voting.pattern, fill = voting.pattern, color = voting.pattern, weight = new.weights)) +
          #geom_density(alpha = 0.4, adjust = 2) +
          geom_histogram(bins = 5, alpha = 0.8) +
            facet_wrap(voting.pattern~issue.variable, labeller = label_value, ncol = 6) +
              scale_x_continuous(breaks = seq(1, 6, 1)) +
                labs(title = 'Distribution of Switch to D and Switch to R on Issue variables',
                    subtitle = 'X axis is of scale 1 to 5, where 1 means strongly support and 5 means strongly oppose') +
                  ylab('Percentage') +
                  theme_bw() +
                    theme(text = element_text(size = 16),
                        axis.text = element_text(size = 14)) +
                      scale_color_viridis_d(name = 'Voting Pattern') +
                        scale_fill_viridis_d(name = 'Voting Pattern')
```



## Question 2

```{r data.manipulation.2, echo = TRUE}
WTHH.df.gather2 <- WTHH.df.gather %>%
                    mutate(voting.pattern2 = ifelse(voting.pattern %in% c('Switch to D', 'Switch to R'), 'Swing Voters', ifelse(voting.pattern == 'Loyal Democrats', 'Loyal Democrats', ifelse(voting.pattern == 'Loyal Republicans', 'Loyal Republicans', NA)))) %>%
                      mutate(voting.pattern2 = factor(voting.pattern2, levels = c('Loyal Democrats', 'Swing Voters', 'Loyal Republicans')))


```

```{r question.2, echo = TRUE, fig.width = 17, fig.height = 10, warning = FALSE}
WTHH.df.gather2 %>% filter(value != 6) %>%
  group_by(voting.pattern2, issue.variable) %>%
    mutate(total.weight = sum(weight_DFP)) %>%
  ungroup() %>%
    mutate(new.weights = weight_DFP/total.weight)%>%
      filter(voting.pattern2 %in% c('Swing Voters', 'Loyal Democrats', 'Loyal Republicans')) %>%
        ggplot(aes(x = value, group = voting.pattern2, fill = voting.pattern2, color = voting.pattern2, weight = new.weights)) +
          #geom_density(alpha = 0.4, adjust = 3, position = 'stack') +
          geom_histogram(bins = 5, alpha = 0.8) +
            facet_wrap(voting.pattern2~issue.variable, labeller = label_value, ncol = 6) +
              scale_x_continuous(breaks = seq(1, 6, 1)) +
                labs(title = 'Distribution of Swing Voters, Loyal Democrats and Loyal Republican on Issue variables',
                    subtitle = 'X axis is of scale 1 to 5, where 1 means strongly support and 5 means strongly oppose') +
                  ylab('Percentage') +
                  theme_bw() +
                    theme(text = element_text(size = 16),
                        axis.text = element_text(size = 14)) +
                          scale_color_viridis_d(name = 'Voting Pattern') +
                            scale_fill_viridis_d(name = 'Voting Pattern')

```


## Question 3

```{r question.3.a, echo = TRUE, warning = FALSE, fig.width = 10, fig.height = 8}
WTHH.df2 <- WTHH.df %>%
              mutate(swing.voters = ifelse(voting.pattern %in% c('Switch to D', 'Switch to R'), 1, 0)) %>%
                mutate(swing.voters = factor(swing.voters),
                       new.weights = ifelse(swing.voters == 0, 1.0, 6.5)) %>% 
                  filter(M4A != 6 & GREENJOB != 6 & WEALTH != 6 &  MARLEG !=6 & ICE != 6 & GUNS != 6) %>%
                    mutate(M4A = factor(M4A)) %>%
                      mutate(GREENJOB = factor(GREENJOB)) %>%
                        mutate(WEALTH = factor(WEALTH)) %>%
                          mutate(MARLEG = factor(MARLEG)) %>%
                            mutate(ICE = factor(ICE)) %>%
                              mutate(GUNS = factor(GUNS))

summary(WTHH.df2$swing.voters)

swing.voters.on.issue.model <- glm(swing.voters ~ M4A + GREENJOB + WEALTH + MARLEG + ICE + GUNS, data = WTHH.df2, family = binomial, weights = new.weights)

fitted.val <- fitted.values(swing.voters.on.issue.model)
residuals <- residuals(swing.voters.on.issue.model, type = 'response')
summary(swing.voters.on.issue.model)

# issue.df <- expand.grid(M4A = 1:5, GREENJOB = 1:5, WEALTH = 1:5, MARLEG = 1:5, ICE = 1:5, GUNS = 1:5)
# predicted <- predict(swing.voters.on.issue.model, newdata = issue.df, type = 'response')
# issue.df <- data.frame(issue.df, swing.voters  = as.vector(predicted))

data.frame(WTHH.df2, fitted.val = as.vector(fitted.val)) %>%
  ggplot(aes(x = fitted.val, weight = new.weights)) +
    geom_histogram(bins = 10) +
    #geom_density() +
      theme_bw() +
        ggtitle('Distibution of fitted values of model with Issue variables as predictors') +
          scale_x_continuous(limits = c(0, 1.0), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1.0)) +
            xlab('Fitted Values') +
              theme(text = element_text(size = 16),
                        axis.text = element_text(size = 14))

data.frame(WTHH.df2, fitted.val = as.vector(fitted.val), residuals = as.vector(residuals)) %>%
  ggplot(aes(x = fitted.val, y = residuals, weight = new.weights)) +
    geom_point() +
      geom_smooth(method = 'loess', method.args = list(degree = 1)) +
        xlab('Fitted Values') +
          ylab('Residuals') +
            ggtitle('Fitted values vs Residuals for model with Issue variables as predictors') +
              theme_bw() +
                theme(text = element_text(size = 16),
                        axis.text = element_text(size = 14))

              
```

```{r question.3.b, echo = TRUE, warning = FALSE, fig.width = 10, fig.height = 8}
WTHH.df2 <- WTHH.df %>%
              mutate(swing.voters = ifelse(voting.pattern %in% c('Switch to D', 'Switch to R'), 1, 0)) %>%
                mutate(swing.voters = factor(swing.voters),
                       new.weights = ifelse(swing.voters == 0, 1.0, 6.5)) %>% 
                  filter(POP_1 !=6 & POP_2 != 6 & POP_3 != 6) %>%
                    mutate(POP_1 = factor(POP_1)) %>%
                      mutate(POP_2 = factor(POP_2)) %>%
                        mutate(POP_3 = factor(POP_3))

swing.voters.on.pop.model <- glm(swing.voters ~ POP_1 + POP_2 + POP_3, data = WTHH.df2, family = binomial, weights = new.weights)
fitted.val <- fitted.values(swing.voters.on.pop.model)
residuals <- residuals(swing.voters.on.pop.model, type = 'response')

# pop.df <- expand.grid(POP_1 = 1:5, POP_2 = 1:5, POP_3 = 1:5)
# predicted <- predict(swing.voters.on.pop.model, newdata = pop.df, type = 'response')
# pop.df <- data.frame(pop.df, swing.voters  = as.vector(predicted))

data.frame(WTHH.df2, fitted.val = as.vector(fitted.val)) %>%
  ggplot(aes(x = fitted.val, weight = new.weights)) +
    geom_histogram(bins = 10) +
    #geom_density() +
      theme_bw() +
        labs('Distibution of fitted values of model with populism variables as predictors') +
          scale_x_continuous(limits = c(0, 1.0), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1.0)) +
            xlab('Fitted Values') +
              theme(text = element_text(size = 16),
                        axis.text = element_text(size = 14))

data.frame(WTHH.df2, fitted.val = as.vector(fitted.val), residuals = as.vector(residuals)) %>%
  ggplot(aes(x = fitted.val, y = residuals, weight = new.weights)) +
    geom_point() +
      geom_smooth(method = 'loess', method.args = list(degree = 1)) +
        xlab('Fitted Values') +
          ylab('Residuals') +
            ggtitle('Fitted values vs Residuals for model with Populism variables as predictors') +
              theme_bw() +
                theme(text = element_text(size = 16),
                        axis.text = element_text(size = 14))

summary(swing.voters.on.pop.model)
```

